In [1]:
import numpy as np

In [2]:
x=np.array([1,2,34])
N=4
def vander(cha):
    if cha==True:
        
        return np.column_stack([x**i for i in range(N)])
    else:
        return np.column_stack([x**(N-1-i) for i in range(N)])
a=vander(True)
b=vander(False)

print("For increasing = True \n",a)
print("For increasing = False \n",b)


For increasing = True 
 [[    1     1     1     1]
 [    1     2     4     8]
 [    1    34  1156 39304]]
For increasing = False 
 [[    1     1     1     1]
 [    8     4     2     1]
 [39304  1156    34     1]]
